export const SPECIALTY_OPTIONS = [
    "Cardiology",
    "Dermatology",
    "Pediatrics",
    "Neurology",
    "General Physician",
    "Gastroenterology",
    "Pulmonology",
    "Family Medicine",
    "Orthopedics",
    "Psychiatry",
    "Radiology",
    "Surgeon",
    "Urology",
    "Gynecology",
    "Dental",
    "Ophthalmology",
    "ENT Specialist",
]
