export enum AppointmentStatus {
  BOOKED = "BOOKED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  NO_SHOW = "NO_SHOW",
  PENDING = "PENDING",
  PAYMENT_FAILED_HOLD = "PAYMENT_FAILED_HOLD",
  EXPIRED = "EXPIRED",
  RESCHEDULED = "RESCHEDULED",
  REASSIGNED = "REASSIGNED",
}
